language: node_js
node_js:
  - "stable"
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  ## Could you please confirm that you have 
  #+ the environment variable below set up with a token?
  #+ If you follow this weeks lab, there's an example on
  #+ subverting the token process and using their OAuth
  #+ app from the market place
  github_token: $github_token
  local_dir: build
  on:
    branch: master
  #!/bin/bash
  now public --token=$NOW_TOKEN

before_install:
  - "npm config set spin false"
  - npm i -g now